### PR TITLE
Add "online signing"

### PR DESCRIPTION
**Pull request by paulehoffman**

### CODE REVIEW

**Comment by wkumari** [comment]
Not sure if it is worth it, but it might be worth adding "and then possibly caching them" somewhere around the "create the required additional records when requests come in to the authoritative server" bit. 

'm perfectly fine with "nah, that could be inferred", but I've found many people don't consider that...

**Comment by paulehoffman** [comment]
If we talk about caching, then we also have to talk about lifetimes, and then ... So, I'd prefer not.

**Comment by kfujiwara** [comment]
I don't prefer "create a zone file" because a zone file is not necessary.
BIND 9's sign with DNS update mode, whole zone information is located at BIND 9's on memory database (and journal file).

I don't prefer "the required additional records". "additional records" is not clear. People may consider "additional records" as "Additional Section" or "Glue".
I prefer "RRSIG and NSEC/NSEC3 records". (or signature and authenticated denial of existence)

RFC 4470 specifies idea of "On-line Signing".
Does RFC 4470 have good terms ?
"generating and signing these records on demand" is one idea.

**Comment by paulehoffman** [comment]
Thanks for noticing that 4470 has a definition of "on-line signing". I looked for "online signing" in RFCs, and didn't find it. (I do not know why the RFC Editor did not copy edit that RFC well.) I'm going to close this PR and start a new one with that definition (although I will expand it to also cover RRSIGs).

**Pull request closed without merging**
