### PR TITLE
Definitions from ter doc

### PR DESCRIPTION
**Pull request by paulehoffman**

### CODE REVIEW

**Comment by kfujiwara** [comment]
RFC 8499 cited/quoted definitions from the original RFCs.
Do you change the policy to refer only ?
Then, all other words need to be changed.

**Comment by paulehoffman** [comment]
Good point, I'll make direct quotes.

**Comment by paulehoffman** [comment]
In looking further, there are no good quotations in any of those RFCs for these terms; the terms are just used loosely. I think the current text in the PR is good enough. Please verify and merge when ready.

**Comment by moonshiner** [comment]
Agree with Paul on "no good quotations".  It will be good to use current text and listen for feedback.

**Pull request merged**
